development:
  adapter: postgresql
  encoding: unicode
  database: restaurante-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: restaurante-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: restaurante-prod
  pool: 5
  host: localhost
  username: action
  password: